from enum import Enum


class MessageType(Enum):
    PRIVATE_MESSAGE = "PRIVATE_MESSAGE"
    GROUP_MESSAGE_REQUEST = "GROUP_MESSAGE_REQUEST"
    ORDERED_GROUP_MESSAGE = "ORDERED_GROUP_MESSAGE"
    HEARTBEAT = "HEARTBEAT"
    ELECTION = "ELECTION"
    COORDINATOR = "COORDINATOR"
