from enum import Enum


class MessageType(Enum):
    PRIVATE_MESSAGE = "PRIVATE_MESSAGE"
    GROUP_MESSAGE_REQUEST = "GROUP_MESSAGE_REQUEST"
    ORDERED_GROUP_MESSAGE = "ORDERED_GROUP_MESSAGE"
    HEARTBEAT = "HEARTBEAT"
    HEARTBEAT_ACK = "HEARTBEAT_ACK"
    ELECTION = "ELECTION"
    COORDINATOR = "COORDINATOR"
    UPDATE_LIST = "UPDATE_NODE_LIST"
    SNAPSHOT_MARKER = "SNAPSHOT_MARKER"
    SNAPSHOT_REPORT = "SNAPSHOT_REPORT"
    ORDER_STATE_REQUEST = "ORDER_STATE_REQUEST"
    ORDER_STATE_RESPONSE = "ORDER_STATE_RESPONSE"
